In [ ]:
# Uczenie maszynowe LAB1

# Pytanie 1.1
# Napisz funkcję kwadraty, która dla danej listy input_list zawierającej liczby zwraca nową listę output_list,
# która zawiera kwadraty liczb dodatnich z input_list. Użyj list comprehension!

def kwadraty(input_list):
    output_list = [x*x for x in input_list if x > 0]
    return output_list


In [ ]:
# pytanie 1.2
# Za pomocą jednowierszowego polecenia utwórz następującą macierz jako obiekt typu `numpy.array`:
# M=[12⋯101112⋯20⋮⋮⋱⋮4142⋯50]
# Wypisz ją na ekran. Macierz na 10 kolumn i pięć wierszy, wejścia to liczby od 1 do 50.

import numpy as np
x = np.arange(1, 51)
x = x.reshape(5, 10)
print(x)

In [13]:
# Testy
import numpy as np
x = np.arange(16)
x = x.reshape(4,4)
print(x)

A = np.array([[-4,-2],[5,5]])
print(A)

# np.inv(np.dot(A, A.T))
B = np.linalg.inv(np.dot(A, A.T))
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[-4 -2]
 [ 5  5]]
[[0.5 0.3]
 [0.3 0.2]]


In [ ]:
# Pytanie 1.3
# Napisz funkcję, która dla danej macierzy zwróci jej:
# liczbę elementów, kolumn i wierszy
# wektory średnich po wierszach i kolumnach
# kolumnę numer 2 - licząc od zera
# wiersz numer 3 - licząc od zera

def wlasciwosci_macierzy(A):
    liczba_elementow = A.size
    liczba_kolumn =  A.shape[1]
    liczba_wierszy =  A.shape[0]
    srednie_wg_wierszy =  A.mean(axis=1)
    srednie_wg_kolumn =  A.mean(axis=0)
    kolumna_2 =  A[:,2]
    wiersz_3 =  A[3,:]
    return (
        liczba_elementow, liczba_kolumn, liczba_wierszy, 
        srednie_wg_wierszy, srednie_wg_kolumn,
        kolumna_2, wiersz_3)

In [ ]:
# Napisz funkcje, które obliczą:
# iloczyn macierzy A z wektorem x 
# iloczyn macierzy A⋅B
# macierz odwrotną (A⋅AT)−1
# wynik działania (A⋅B)T−BT⋅AT
# Przyjmij, że macierze i wektory wejściowe reprezento

def dzialanie1(A, x):
    """ iloczyn macierzy A z wektorem x """
    return np.dot(A, x)

def dzialanie2(A, B):
    """ iloczyn macierzy A · B """
    return np.dot(A, B)

def dzialanie3(A):
    """ odwrotność iloczynu A · A.T """
    return np.linalg.inv(np.dot(A, A.T))

def dzialanie4(A, B):
    """ wynik działania (A · B)^T - B^T · A^T """
    return np.dot(A, B).T - (np.dot(B.T, A.T))